# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnTheDot' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OnTheDot
  pod 'Alamofire'
end
